services:
  php:
    build:
      dockerfile: Dockerfile
    container_name: ambiente-php
    ports:
      - 8080:80
    volumes:
      - ./public:/var/www/html
      - ./vendor:/var/www/vendor
      - ./app:/var/www/app
      - ./app/logs:/var/log/apache2
    command: bash -c "php -S 0.0.0.0:80 -t /var/www/html"
    links:
      - db
      - memcached
    networks:
      - network

  db:
    image: mysql:latest
    container_name: mysql-php
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-dev:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - network

  memcached:
    image: memcached:latest
    container_name: memcached-php
    ports:
      - "11211:11211"
    command: memcached -m 64m
    networks:
      - network

  https-portal:
    image: steveltn/https-portal:1
    volumes:
      - ./certificados-dev:/var/lib/https-portal
    ports:
      - '80:80'
      - '443:443'
    links:
      - php
    restart: always

    environment:
      DOMAINS: '360help.local -> http://php:80'
      STAGE: 'local'
      FORCE_RENEW: 'false'
    networks:
      - network

networks:
  network: