services:
  php:
    build:
      dockerfile: Dockerfile
    container_name: ambiente-php
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/html
      - ./vendor:/var/www/vendor
      - ./app:/var/www/app
      - ./app/logs/:/var/log/apache2
      - ./php.ini:/usr/local/etc/php/php.ini
    links:
      - db
      - memcached
    networks:
      - network
    env_file:
      - .env

  db:
    image: mysql:latest
    container_name: mysql-php
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-dev:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - network

  memcached:
    image: memcached:latest
    container_name: memcached-php
    ports:
      - "11211:11211"
    command: memcached -m 64m
    networks:
      - network

networks:
  network: