services:
  php:
    build:
      dockerfile: Dockerfile
    container_name: ambiente-php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html
      - ./app:/var/www/app
      - ./vendor:/var/www/vendor
      - ./app/logs/:/var/log/apache2
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - network
    env_file:
      - .env

  db:
    image: mysql:8.0.33
    ports: 
      - "3306:3306"
    container_name: mysql-php
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - network

  memcached:
    image: memcached:latest
    container_name: memcached-php
    command: memcached -m 64m
    networks:
      - network

networks:
  network:

volumes:
  mysql-data: