services:
  php:
    build:
      dockerfile: Dockerfile
    container_name: ambiente-php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html
      - ./app:/var/www/app
      - ./vendor:/var/www/vendor
      - ./app/logs/:/var/log/apache2
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - ./certs:/etc/apache2/certs:ro
      - ./apache-ssl-prod.conf:/etc/apache2/sites-available/default-ssl.conf:ro
    networks:
      - network
    env_file:
      - .env

  db:
  image: mysql:8.0.33
  container_name: mysql-php
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  volumes:
    - mysql-data:/var/lib/mysql
    - ./certs/mysql:/etc/mysql/certs:ro
  command: >
    --ssl-ca=/etc/mysql/certs/origin.pem
    --ssl-cert=/etc/mysql/certs/origin.pem
    --ssl-key=/etc/mysql/certs/origin.key
  ports:
    - "3306:3306"
  networks:
    - network


  memcached:
    image: memcached:latest
    container_name: memcached-php
    command: memcached -m 64m
    networks:
      - network

networks:
  network:

volumes:
  mysql-data: