services:
  php:
    build:
      dockerfile: Dockerfile
    container_name: ambiente-php
    ports:
      - 80:80
    volumes:
      - ./app/logs/:/var/log/apache2
      - ./config/php.ini:/usr/local/etc/php/php.ini
    networks:
      - network
    env_file:
      - .env

  db:
    image: mysql:8.0.33
    container_name: mysql-php
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - network

  memcached:
    image: memcached:latest
    container_name: memcached-php
    command: memcached -m 64m
    networks:
      - network

networks:
  network:

volumes:
  mysql-data: