----- Insere 10 categorias -----

INSERT INTO `categorias` (`nome`, `descricao`, `empresa_id`, `ordem`, `ativo`)
VALUES
('Integrações de Frete', 'Documentação e tutoriais sobre integrações de frete.', 1, 12, 1),
('Blog', 'Orientações para configurar e gerenciar o blog da sua empresa.', 1, 13, 1),
('Integrações de Pagamento', 'Informações sobre como integrar sistemas de pagamento.', 1, 14, 1),
('Configurações de Conta', 'Ajuda para configurar e gerenciar sua conta.', 1, 15, 1),
('Relatórios e Análises', 'Guias sobre como gerar e entender relatórios e análises.', 1, 16, 1),
('Gerenciamento de Produtos', 'Instruções para adicionar e gerenciar produtos na plataforma.', 1, 17, 1),
('Suporte ao Cliente', 'Recursos para configurar e otimizar o suporte ao cliente.', 1, 18, 1),
('Integrações de CRM', 'Dicas e tutoriais sobre integrações com sistemas de CRM.', 1, 19, 1),
('Configurações de E-mail', 'Ajuda para configurar e gerenciar o e-mail da empresa.', 1, 20, 1),
('Automatizações', 'Documentação sobre como configurar e usar automatizações na plataforma.', 1, 21, 1);

----- Insere 50 artigos -----

INSERT INTO `artigos` (`titulo`, `usuario_id`, `empresa_id`, `categoria_id`, `ordem`, `ativo`)
VALUES
('Como Configurar Frete para Diferentes Regiões', 1, 1, 1, 4, 1),
('Otimizando o Frete para Reduzir Custos', 1, 1, 1, 5, 1),
('Integração com Transportadoras Parceiras', 1, 1, 1, 6, 1),
('Como Criar um Novo Post no Blog', 1, 1, 2, 7, 1),
('Estratégias para Aumentar o Tráfego do Blog', 1, 1, 2, 8, 1),
('Melhores Práticas de SEO para o Blog', 1, 1, 2, 9, 1),
('Configurando Gateways de Pagamento', 1, 1, 3, 10, 1),
('Resolução de Problemas Comuns em Pagamentos', 1, 1, 3, 11, 1),
('Implementando Pagamentos Recorrentes', 1, 1, 3, 12, 1),
('Como Alterar Suas Informações de Conta', 1, 1, 4, 13, 1),
('Segurança de Conta: Dicas Importantes', 1, 1, 4, 14, 1),
('Personalizando Suas Preferências de Conta', 1, 1, 4, 15, 1),
('Gerando Relatórios de Vendas', 1, 1, 5, 16, 1),
('Analisando o Desempenho de Produtos', 1, 1, 5, 17, 1),
('Como Exportar Relatórios para Excel', 1, 1, 5, 18, 1),
('Adicionando Novos Produtos ao Catálogo', 1, 1, 6, 19, 1),
('Gerenciamento de Estoque para Produtos', 1, 1, 6, 20, 1),
('Dicas para Melhorar a Descrição de Produtos', 1, 1, 6, 21, 1),
('Configurações Básicas de Suporte ao Cliente', 1, 1, 7, 22, 1),
('Como Criar e Gerenciar Tickets de Suporte', 1, 1, 7, 23, 1),
('Automatizando Respostas de Suporte', 1, 1, 7, 24, 1),
('Integrando CRM com sua Plataforma', 1, 1, 8, 25, 1),
('Sincronização de Dados entre CRM e Plataforma', 1, 1, 8, 26, 1),
('Melhores Práticas para Uso do CRM', 1, 1, 8, 27, 1),
('Configuração Inicial de E-mail da Empresa', 1, 1, 9, 28, 1),
('Gerenciamento de Filtros e Regras de E-mail', 1, 1, 9, 29, 1),
('Como Configurar Respostas Automáticas no E-mail', 1, 1, 9, 30, 1),
('Criando Fluxos de Trabalho Automatizados', 1, 1, 10, 31, 1),
('Como Usar Templates de Automatização', 1, 1, 10, 32, 1),
('Monitoramento e Ajuste de Automatizações', 1, 1, 10, 33, 1),
('Frete Expresso: Vantagens e Desvantagens', 1, 1, 1, 34, 1),
('Usando APIs de Frete para Cálculo de Custos', 1, 1, 1, 35, 1),
('Integrações Avançadas de Frete', 1, 1, 1, 36, 1),
('Gerenciamento de Categorias no Blog', 1, 1, 2, 37, 1),
('Como Agendar Posts no Blog', 1, 1, 2, 38, 1),
('Integração do Blog com Redes Sociais', 1, 1, 2, 39, 1),
('Pagamentos Internacionais: O que Considerar', 1, 1, 3, 40, 1),
('Facilitando Pagamentos com QR Code', 1, 1, 3, 41, 1),
('Resolvendo Disputas de Pagamento', 1, 1, 3, 42, 1),
('Revisão de Permissões de Conta', 1, 1, 4, 43, 1),
('Gerenciando Múltiplas Contas de Usuário', 1, 1, 4, 44, 1),
('Como Configurar Autenticação em Duas Etapas', 1, 1, 4, 45, 1),
('Personalizando Relatórios Avançados', 1, 1, 5, 46, 1),
('Monitoramento de Indicadores Chave de Desempenho (KPI)', 1, 1, 5, 47, 1),
('Analisando Tendências de Mercado com Relatórios', 1, 1, 5, 48, 1),
('Editando Produtos em Massa', 1, 1, 6, 49, 1),
('Como Fazer Backup de Dados de Produtos', 1, 1, 6, 50, 1),
('Personalizando Layouts de Produtos', 1, 1, 6, 51, 1);

----- Insere 47 artigos -----


INSERT INTO `conteudos` (`ativo`, `artigo_id`, `empresa_id`, `tipo`, `titulo`, `titulo_ocultar`, `conteudo`, `url`, `ordem`)
VALUES
(1, 701, 1, 1, NULL, 1, '&lt;p&gt;Este é um exemplo de conteúdo formatado com &lt;strong&gt;negrito&lt;/strong&gt; e &lt;i&gt;itálico&lt;/i&gt;.&lt;/p&gt;', '', 1),
(1, 702, 1, 1, NULL, 1, '&lt;p&gt;Utilize listas para organizar suas ideias:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;Item 1&lt;/li&gt;&lt;li&gt;Item 2&lt;/li&gt;&lt;/ul&gt;', '', 1),
(1, 704, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 705, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 706, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 707, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 708, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 709, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 710, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 711, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 712, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 713, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 714, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 715, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 716, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 717, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 718, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 719, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 720, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 721, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 722, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 723, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 724, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 725, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 726, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 727, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 728, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 729, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 730, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 731, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 732, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 733, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 734, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 735, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 736, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 737, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 738, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 739, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 740, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 741, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 742, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 743, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 744, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 745, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 746, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 747, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1),
(1, 748, 1, 1, NULL, 1, '&lt;p&gt;Adicione &lt;a href=&quot;#&quot;&gt;links&lt;/a&gt; ao seu conteúdo para enriquecer a navegação.&lt;/p&gt;', '', 1)